# Generated by Django 3.2.4 on 2022-01-24 00:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.CharField(auto_created=True, default='1', max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('total', models.FloatField()),
                ('gst', models.FloatField()),
                ('discount', models.FloatField(null=True)),
                ('round', models.FloatField(null=True)),
                ('g_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pro_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('M_date', models.DateField()),
                ('E_date', models.DateField()),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.product')),
                ('pro_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.batch', to_field='batch')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_name', models.CharField(default='default', max_length=20)),
                ('cost', models.FloatField()),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.party')),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.batch', to_field='batch')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quan', models.IntegerField(null=True)),
                ('rate', models.FloatField()),
                ('cost', models.FloatField()),
                ('igst', models.FloatField(null=True)),
                ('cgst', models.FloatField(null=True)),
                ('sgst', models.FloatField(null=True)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.product')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.product'),
        ),
    ]
