# Generated by Django 4.0.1 on 2022-01-21 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('add', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('pro_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=300)),
                ('pro_batch', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('M_date', models.DateField()),
                ('E_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt_name', models.CharField(default='default', max_length=20)),
                ('cost', models.FloatField()),
                ('party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.party')),
                ('pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bill.stock')),
            ],
        ),
    ]
