# Generated by Django 3.2.4 on 2022-01-24 00:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='batch',
        ),
        migrations.AddField(
            model_name='purchase',
            name='country',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product', chained_model_field='product', default=None, on_delete=django.db.models.deletion.CASCADE, to='bill.batch'),
        ),
    ]
